### ISSUE TITLE
Données plus mises à jour ?

### ISSUE THREAD

**Issue by menbati** [139bercy/decp-projet#82]
Bonjour,
Il semblerait que les données ne soient plus mise à jour sur le site economie.gouv.fr ( https://data.economie.gouv.fr/explore/dataset/decp_augmente/information/ )

Le dernier changement est en date du 26 octobre.
Le jeu de données est toujours valide n'est ce pas ?
Cordialement,

**Comment by menbati** [comment]
Je viens de voir que la CI plante sur cette ligne https://github.com/139bercy/decp-augmente/blob/flux_ci/gestion_flux.py#L128

**Comment by desrousseaux** [comment]
Bonjour,

La nouvelle version des decp qui est mise à jour quotidiennement est disponible dans quatre nouveaux fichiers indiqués avec la mention V3 : https://data.economie.gouv.fr/pages/donnees-essentielles-de-la-commande-publique/

Ces fichiers sont séparés en marchés et concessions d'une part, puis valides ou invalides selon des règles de gestion d'autre part.

**Comment by menbati** [comment]
Merci @desrousseaux je n'avais pas vu passer l'info. Je ferme le ticket
